name: Build and Test
on:
  push:
    branches:
      - 'main'
jobs:
  test:
    runs-on: macos-latest
    timeout-minutes: 10
    steps:
      - name: Check out repository
        uses: actions/checkout@v3
      - name: Build package
        run: swift build -v
      - name: Run tests
        run: swift test -v
